# Session 13

prepossing data for modeling
imoptant libraries 
numpy, pandas , matplotlib, seaborn

Data preprocessing meaning converting data in to format which is suitable for input to a machine learning model

tabular data needs more processing , more handling than image data

most havely preprocessing done on tabular(structural) data set 

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Data 13.csv')

In [3]:
df.head(11)

Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Germany  40.0      NaN       Yes
5    France  35.0  58000.0       Yes
6     Spain   NaN  52000.0        No
7    France  48.0  79000.0       Yes
8   Germany  50.0  83000.0        No
9    France  37.0  67000.0       Yes
10   France  37.0  67000.0       Yes

In [4]:
#1st step handeling missing value and duplicate values
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool

In [5]:
# there are duplicated value in 11 row
# droping duplicate values
df.drop_duplicates(inplace = True)

In [6]:
df
# 11 row is removed because it was duplicateof 10th row 

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [7]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

there are 4 columns an in those between age nad salary having 1 value is null for each
<br>dealing with null value 
<br>condition 1 = if we have 100 rows in colulmn  and 40 are the null then **drop this column** and we will do not consider for that model 


## null values
### now there is no such condition so filling these null values 

### 1.filling with perticular value
**filling with zeros or one if null values are less than 40 or somthing 20 to 25**

In [8]:
print(df.fillna(0))

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      0.0       Yes
5   France  35.0  58000.0       Yes
6    Spain   0.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [9]:
print(df.fillna(1))

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      1.0       Yes
5   France  35.0  58000.0       Yes
6    Spain   1.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


### 2. droping the entire row not column (entire entry ) this condition is applicable when null values are so much less like 5 to 10 percent 

In [13]:
df.dropna()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


### 3. best way to deal with null value is fill with by avg (calculate mean)
### 4. if it is categorical value use mode 


In [14]:
avg_age= df['Age'].mean()
avg_salary = df['Salary'].mean()

In [18]:
print(avg_age,'\n',avg_salary)

38.77777777777778 
 63777.77777777778


In [20]:
df['Age'].replace(np.nan,avg_age,inplace = True)
df['Salray'].replace(np.nan,avg_salary,inplace =True)
# df['Salray'].replace(x,y,inplace =True) x replace with y in salary column 


In [21]:
df

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [22]:
df.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

## Using scikit-learn 

In [23]:
df2 = pd.read_csv('Data 13.csv')

In [24]:
# droping duplicates
df2.drop_duplicates(inplace = True)
X = df2.iloc[:, :-1].values
y = df2.iloc[:,-1].values

In [25]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values = np.nan,strategy = 'mean')
# if missing values are categorical use strategy as 'mode'
imp.fit(X[:,1:3])
X[:,1:3] = imp.fit_transform(X[:,1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## Normlizatio or standersization
variace of data is huge 

1. standard scalar
2. min max

In [30]:
# 1. standard Scalar
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X[:, 1:] = sc.fit_transform(X[:, 1:])
X

array([['France', 0.758874361590019, 0.7494732544921677],
       ['Spain', -1.7115038793306814, -1.4381784072687531],
       ['Germany', -1.2755547779917342, -0.8912654918285229],
       ['Spain', -0.1130238410878753, -0.253200423814921],
       ['Germany', 0.17760889313808945, 6.632191985654332e-16],
       ['France', -0.5489729424268225, -0.5266568815350361],
       ['Spain', 0.0, -1.0735697969752662],
       ['France', 1.3401398300419485, 1.3875383225057696],
       ['Germany', 1.6307725642679132, 1.7521469327992565],
       ['France', -0.2583402082008577, 0.29371249162530916]], dtype=object)

In [35]:
X[:,2].var() # now data in unit variance 

1.0000000000000002

In [36]:
X[:,1].var()

1.0

Handling Categorical data 

In [37]:
# What is categorical data 
# example yes or no, male or female
# data which is not numrical 
# in this data 1st column is categorical- france spain Germany

1. one hot encoding

In [38]:
dummy1 = pd.get_dummies(df['Country'])
dummy1


France  Germany  Spain
0       1        0      0
1       0        0      1
2       0        1      0
3       0        0      1
4       0        1      0
5       1        0      0
6       0        0      1
7       1        0      0
8       0        1      0
9       1        0      0

In [40]:
df = pd.concat([dummy1, df], axis =1)
df

France  Germany  Spain  Country        Age        Salary Purchased
0       1        0      0   France  44.000000  72000.000000        No
1       0        0      1    Spain  27.000000  48000.000000       Yes
2       0        1      0  Germany  30.000000  54000.000000        No
3       0        0      1    Spain  38.000000  61000.000000        No
4       0        1      0  Germany  40.000000  63777.777778       Yes
5       1        0      0   France  35.000000  58000.000000       Yes
6       0        0      1    Spain  38.777778  52000.000000        No
7       1        0      0   France  48.000000  79000.000000       Yes
8       0        1      0  Germany  50.000000  83000.000000        No
9       1        0      0   France  37.000000  67000.000000       Yes

In [42]:
# perchase is also categorical value 
dummy2 = pd.get_dummies(df['Purchased'])
dummy2

No  Yes
0   1    0
1   0    1
2   1    0
3   1    0
4   0    1
5   0    1
6   1    0
7   0    1
8   1    0
9   0    1

In [43]:
X

array([['France', 0.758874361590019, 0.7494732544921677],
       ['Spain', -1.7115038793306814, -1.4381784072687531],
       ['Germany', -1.2755547779917342, -0.8912654918285229],
       ['Spain', -0.1130238410878753, -0.253200423814921],
       ['Germany', 0.17760889313808945, 6.632191985654332e-16],
       ['France', -0.5489729424268225, -0.5266568815350361],
       ['Spain', 0.0, -1.0735697969752662],
       ['France', 1.3401398300419485, 1.3875383225057696],
       ['Germany', 1.6307725642679132, 1.7521469327992565],
       ['France', -0.2583402082008577, 0.29371249162530916]], dtype=object)

## for creating Dummy variables One hot Encoder 

In [46]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[0])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, 0.758874361590019, 0.7494732544921677],
       [0.0, 0.0, 1.0, -1.7115038793306814, -1.4381784072687531],
       [0.0, 1.0, 0.0, -1.2755547779917342, -0.8912654918285229],
       [0.0, 0.0, 1.0, -0.1130238410878753, -0.253200423814921],
       [0.0, 1.0, 0.0, 0.17760889313808945, 6.632191985654332e-16],
       [1.0, 0.0, 0.0, -0.5489729424268225, -0.5266568815350361],
       [0.0, 0.0, 1.0, 0.0, -1.0735697969752662],
       [1.0, 0.0, 0.0, 1.3401398300419485, 1.3875383225057696],
       [0.0, 1.0, 0.0, 1.6307725642679132, 1.7521469327992565],
       [1.0, 0.0, 0.0, -0.2583402082008577, 0.29371249162530916]],
      dtype=object)

In [47]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [53]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [54]:
z = df['Country'].values
z = le.fit_transform(z)
z

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

In [56]:
print(X)


[[1.0 0.0 0.0 0.758874361590019 0.7494732544921677]
 [0.0 0.0 1.0 -1.7115038793306814 -1.4381784072687531]
 [0.0 1.0 0.0 -1.2755547779917342 -0.8912654918285229]
 [0.0 0.0 1.0 -0.1130238410878753 -0.253200423814921]
 [0.0 1.0 0.0 0.17760889313808945 6.632191985654332e-16]
 [1.0 0.0 0.0 -0.5489729424268225 -0.5266568815350361]
 [0.0 0.0 1.0 0.0 -1.0735697969752662]
 [1.0 0.0 0.0 1.3401398300419485 1.3875383225057696]
 [0.0 1.0 0.0 1.6307725642679132 1.7521469327992565]
 [1.0 0.0 0.0 -0.2583402082008577 0.29371249162530916]]


In [57]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


In [64]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state = 0)

In [65]:
x_train

array([[0.0, 1.0, 0.0, 0.17760889313808945, 6.632191985654332e-16],
       [1.0, 0.0, 0.0, -0.2583402082008577, 0.29371249162530916],
       [0.0, 0.0, 1.0, -1.7115038793306814, -1.4381784072687531],
       [0.0, 0.0, 1.0, 0.0, -1.0735697969752662],
       [1.0, 0.0, 0.0, 1.3401398300419485, 1.3875383225057696],
       [0.0, 0.0, 1.0, -0.1130238410878753, -0.253200423814921],
       [1.0, 0.0, 0.0, 0.758874361590019, 0.7494732544921677],
       [1.0, 0.0, 0.0, -0.5489729424268225, -0.5266568815350361]],
      dtype=object)

In [66]:
x_test

array([[0.0, 1.0, 0.0, -1.2755547779917342, -0.8912654918285229],
       [0.0, 1.0, 0.0, 1.6307725642679132, 1.7521469327992565]],
      dtype=object)

In [67]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [68]:
y_test

array([0, 0])