## NumPy
*Short for Numrical Python,NumPy is a foundation package for numriacal computing in python, ndarray is an efficient multidimentional array  oriented operations*


In [1]:
import numpy as np 

In [6]:
a= np.arange(1000000)
l= list(range(1000000))

In [16]:
# this command for calculating time 
%timeit for i in range(1000): a1 = a*2 

SyntaxError: invalid syntax (<unknown>, line 1)

In [9]:
# %timeit for i in range(1000): l1 = l*2

In [10]:
a = np.arange(5)
a*2

array([0, 2, 4, 6, 8])

In [11]:
l = [1,2,3,4,5]
l*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [18]:
data =[1,2,3,4,5]
a1= np.array(data)
a1

array([1, 2, 3, 4, 5])

In [19]:
type(a1)

numpy.ndarray

In [20]:
data= [[1,2,3,4,5],[1,2,3,4,5]]
a1 = np.array(data)
a1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [21]:
a1.shape

(2, 5)

In [22]:
a1.dtype

dtype('int32')

In [24]:
a1.ndim

2

In [27]:
a1 = np.arange(10)

In [29]:
print(a1)
a1.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int32')

In [31]:
a1 = a1.astype("float64")
print(a1.dtype)
a1

float64


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [32]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
zero =np.zeros((3,3,3))
zero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [38]:
zero.ndim

3

In [40]:
np.full((3,3),fill_value =3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [41]:
#identical matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.full((3,3),fill_value =3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [45]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Arithmatics Operations 

In [46]:
a1 = np.array([1,2,3,4,5,6])
a1

array([1, 2, 3, 4, 5, 6])

In [47]:
a1 + 2

array([3, 4, 5, 6, 7, 8])

In [49]:
[1,2,3]+[4]# concatination

[1, 2, 3, 4]

In [50]:
a1 *3

array([ 3,  6,  9, 12, 15, 18])

In [51]:
a1/2 #simple samples of NDRa

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [57]:
6//a1

array([6, 3, 2, 1, 1, 1], dtype=int32)

In [53]:
a1//2

array([0, 1, 1, 2, 2, 3], dtype=int32)

In [54]:
#power operation 
a1 **2

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [55]:
a1 *a1

array([ 1,  4,  9, 16, 25, 36])

In [56]:
a1 **a1

array([    1,     4,    27,   256,  3125, 46656], dtype=int32)

In [58]:
a1 = np.array([1,2,3,4,5,6])
a2 = np.array([3,4,2,1,6,5])

In [60]:
a1>a2

array([False, False,  True,  True, False,  True])

In [62]:
a1<a1

array([False, False, False, False, False, False])

## Indexing and Slicing

In [63]:
a = np.arange(10)

In [64]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a[0]

0

In [66]:
a[-1]

9

In [67]:
a[5]

5

In [68]:
a[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [69]:
a[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
#important object

In [71]:
a2 = np.arange(11)

In [72]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
# replacing values 
a2[:3] = 11
a2

array([11, 11, 11,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
a2[:]= 22

In [78]:
a2

array([22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22])

In [83]:
a1 = np.arange(10)
c1 = a1

In [84]:
c1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
c1[:3] =66

In [86]:
c1

array([66, 66, 66,  3,  4,  5,  6,  7,  8,  9])

In [87]:
a1

array([66, 66, 66,  3,  4,  5,  6,  7,  8,  9])

In [88]:
# so not to change in a1 we need to use copy function
a1 = np.arange(10)
c1 = a1.copy()

In [89]:
c1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
c1[:3]=66
c1

array([66, 66, 66,  3,  4,  5,  6,  7,  8,  9])

In [91]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##  reshaping  

In [92]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [95]:
a.shape #not usefull 1 d (singular not acceptated)

(16,)

In [96]:
#reashape method
a1 = a.reshape((16,1)) # specify both 
a1.shape

(16, 1)

In [97]:
a1.ndim

2

In [98]:
a.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [103]:
a1

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [104]:
#Tanspose 
a1.T

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [102]:
# dot product of matrix (multiplication)
np.dot(a1,a1.T)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15],
       [  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
         26,  28,  30],
       [  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
         39,  42,  45],
       [  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
         52,  56,  60],
       [  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
         65,  70,  75],
       [  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,
         78,  84,  90],
       [  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,
         91,  98, 105],
       [  0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96,
        104, 112, 120],
       [  0,   9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108,
        117, 126, 135],
       [  0,  10,  20,  30,  4

In [106]:
a = np.array ([2,4,3,7,8,2,6,7,1])
a

array([2, 4, 3, 7, 8, 2, 6, 7, 1])

In [108]:
a.sort()
a

array([1, 2, 2, 3, 4, 6, 7, 7, 8])

In [109]:
np.square(a)

array([ 1,  4,  4,  9, 16, 36, 49, 49, 64], dtype=int32)

In [110]:
np.sqrt(a)

array([1.        , 1.41421356, 1.41421356, 1.73205081, 2.        ,
       2.44948974, 2.64575131, 2.64575131, 2.82842712])

In [111]:
np.abs([-1,-4,-5,-14,2])

array([ 1,  4,  5, 14,  2])

In [113]:
a1= np.array([2,5,1,6,5,9])
a2 = np.array([4,3,7,8,2,4])
np.maximum(a1,a2)

array([4, 5, 7, 8, 5, 9])

In [114]:
np.minimum(a1,a2)

array([2, 3, 1, 6, 2, 4])

In [115]:
np.power(a1,a2)

array([     16,     125,       1, 1679616,      25,    6561], dtype=int32)

In [116]:
np.greater(a1,a2)

array([False,  True, False, False,  True,  True])

In [119]:
np.cbrt([8,27,64])

array([2., 3., 4.])

In [120]:
np.mean(a)

4.444444444444445

In [121]:
a.sum()

40

In [122]:
a.min()

1

In [123]:
a.max()

8

In [125]:
a.std()
#standard daviation

2.454524670486058

In [126]:
a.var()

6.024691358024692

In [128]:
a.cumsum() #cumilative sum of element

array([ 1,  3,  5,  8, 12, 18, 25, 32, 40], dtype=int32)

In [129]:
np.median(a)

4.0

In [130]:
#for 2D array 

In [131]:
a = np.arange((25))
a = a.reshape((5,5))

In [132]:
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [133]:
a.mean(axis=1) #axis  1 means along the row

array([ 2.,  7., 12., 17., 22.])

In [134]:
a.mean(axis=0) #axis  0 means along the column

array([10., 11., 12., 13., 14.])

In [135]:
a.var(axis=0)

array([50., 50., 50., 50., 50.])

In [136]:
a.dot(a.T)

array([[  30,   80,  130,  180,  230],
       [  80,  255,  430,  605,  780],
       [ 130,  430,  730, 1030, 1330],
       [ 180,  605, 1030, 1455, 1880],
       [ 230,  780, 1330, 1880, 2430]])

In [137]:
# determinent eigen values 

In [138]:
from numpy.linalg import det, inv, eig

In [139]:
a = np.array([4,6,7,8,4,6,8,9,7]).reshape((3,3))
a

array([[4, 6, 7],
       [8, 4, 6],
       [8, 9, 7]])

In [140]:
det(a)

127.99999999999997

In [141]:
# inverse
inv(a)

array([[-0.203125 ,  0.1640625,  0.0625   ],
       [-0.0625   , -0.21875  ,  0.25     ],
       [ 0.3125   ,  0.09375  , -0.25     ]])

In [142]:
# eigen
eig(a)

(array([19.69625748+0.j        , -2.34812874+0.99246559j,
        -2.34812874-0.99246559j]),
 array([[-0.50577472+0.j        ,  0.21821534-0.34731668j,
          0.21821534+0.34731668j],
        [-0.52069669+0.j        , -0.70840036+0.j        ,
         -0.70840036-0.j        ],
        [-0.68779859+0.j        ,  0.45854899+0.34591175j,
          0.45854899-0.34591175j]]))

In [146]:
a

array([[4, 6, 7],
       [8, 4, 6],
       [8, 9, 7]])

In [145]:
np.concatenate((a,a.T),axis = 1)

array([[4, 6, 7, 4, 8, 8],
       [8, 4, 6, 6, 4, 9],
       [8, 9, 7, 7, 6, 7]])

In [147]:
a = np.arange(64).reshape((8,8))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [148]:
# if we need extracting  only 1 2 3  column

In [149]:
a[:,1:4]

array([[ 1,  2,  3],
       [ 9, 10, 11],
       [17, 18, 19],
       [25, 26, 27],
       [33, 34, 35],
       [41, 42, 43],
       [49, 50, 51],
       [57, 58, 59]])

In [152]:
a[2:5,2:6]

array([[18, 19, 20, 21],
       [26, 27, 28, 29],
       [34, 35, 36, 37]])

In [153]:
import pandas as pd 

In [154]:
df = pd.DataFrame(a)

In [155]:
df

0   1   2   3   4   5   6   7
0   0   1   2   3   4   5   6   7
1   8   9  10  11  12  13  14  15
2  16  17  18  19  20  21  22  23
3  24  25  26  27  28  29  30  31
4  32  33  34  35  36  37  38  39
5  40  41  42  43  44  45  46  47
6  48  49  50  51  52  53  54  55
7  56  57  58  59  60  61  62  63

In [160]:
#if i want to convert ndrf 
X = df.loc[:,:].values
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])